// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated by Swift Playgrounds.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Titanium Core",
    platforms: [
        .iOS("17.0") // 🚀 UPGRADED: Unlocks the SwiftData Database Engine
    ],
    products: [
        .iOSApplication(
            name: "Titanium Core",
            targets: ["AppModule"],
            bundleIdentifier: "com.titanium.core",
            teamIdentifier: "",
            displayVersion: "2.0", // Welcome to Version 2.0
            bundleVersion: "1",
            appIcon: .placeholder(icon: .globe),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
